language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
  - secure: IF95SacFp9vhD1pRD0SECTpWE5xOJtQUEr6nLfDm38Ex5FzWdygHdI6C2hGINgz7IIzvNjXLxAAnRi/myDE3zQNA6jTCESkioFt+nnQTMNjcnHCA0HOV5eNidZLLHf+PrifcY3DtFzesuS6HAXLdqpMprO5/pSLIrnkos0LarBQ=
  - secure: Q1hn7aWS3ntnEqxDiGBb0uKOA/4QkcpJh7ZgmI8Psdj5Pdwkzyih5SlZA+4QkIfkCpSZsug0jQqK+udqxF+BKBjrfVWsp81nYTzEt/FoJT//enkbz2+mHQh5e4Pe4Nu4mpq4lHv7WRgR42Ai9i+OYJ+XZxHfU3mIXJ9zibumC7Y=
